databases:
  - name: rails-first-app_DB
    databaseName: rails_first_app_db
    user: rails_first_app_db_user
    region: singapore

services:
  - type: web
    name: rails-first-app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-first-app_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false